/*
- ------------------------------------------------------------
- "THE BEERWARE LICENSE" (Revision 42):
- diegohamilton26@gmail.com wrote this code. As long as you retain this
- notice, you can do whatever you want with this stuff. If we
- meet someday, and you think this stuff is worth it, you can
- buy me a beer in return,
- Diego Hamilton.
- ------------------------------------------------------------
 */

#ifndef _CIRCULAR_BUFFER_H
#define _CIRCULAR_BUFFER_H

#include <stdlib.h>

/*
- BUF must be a buffer object with a type generated by
  circular_buffer_struct().
- ELEM must be an element (not a pointer) of the buffer element type.
 */

#define circular_buffer_struct(T, SIZE) \
    struct {                            \
        int occup;                      \
        int size;                       \
        int head, tail;                 \
        T data[SIZE];                   \
    }

#define cb_init(BUF, T, SIZE)    \
    do {                         \
        (BUF).size  = SIZE;      \
        (BUF).occup = 0;         \
        (BUF).head  = 0;         \
        (BUF).tail  = 0;         \
    } while (0)

#define cb_size(BUF)       ((BUF).size)
#define cb_full(BUF)       ((BUF).occup == (BUF).size)
#define cb_empty(BUF)      ((BUF).occup == 0)
#define cb_occupation(BUF) ((BUF).occup)

#define cb_reset(BUF)    \
    do {                 \
        (BUF).head  = 0; \
        (BUF).tail  = 0; \
        (BUF).occup = 0; \
    } while (0)

/* When full, cb_push overwrites the oldest element. */
#define cb_push(BUF, ELEM)                                      \
    do {                                                        \
        ((BUF).data)[(BUF).tail] = (ELEM);                      \
        (BUF).tail = ((BUF).tail + 1) % cb_size(BUF);           \
        if (cb_full((BUF))) {                                   \
            (BUF).head = ((BUF).head + 1) % cb_size(BUF);       \
        } else {                                                \
            (BUF).occup = (BUF).occup + 1;                      \
        }                                                       \
    } while (0)

#define cb_pop(BUF, ELEM)                                       \
    do {                                                        \
        if (!cb_empty((BUF))) {                                 \
            (ELEM) = (BUF).data[(BUF).head];                    \
            (BUF).head = ((BUF).head + 1) % cb_size(BUF);       \
            (BUF).occup -= 1;                                   \
        }                                                       \
    } while (0)

#endif
